version: "3"
services:
 app:
  build: .
  volumes:
   - .:/django
  ports:
   - 8000:8000
  environment:
   DEBUG: 1
   SECRET_KEY: 6a67rstg87fmm4-yrw-tydn=o^*n$k$ju&z09f*kdp#10c)#=d
  image: app:django
  container_name: django_project_dev
  command: python manage.py runserver 0.0.0.0:8000